using System.Runtime.CompilerServices;
using Unity.Burst.CompilerServices;

namespace MaxMath
{
    unsafe internal static partial class Operator
    {
        internal static partial class Constant
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal static UInt128 shluint128(UInt128 value, int n) 
            {
                switch (n)
                {
                    case 1:   return new UInt128(value.lo << 1,     (value.hi << 1)  | (value.lo >> (64 - 1)));
                    case 2:   return new UInt128(value.lo << 2,     (value.hi << 2)  | (value.lo >> (64 - 2)));
                    case 3:   return new UInt128(value.lo << 3,     (value.hi << 3)  | (value.lo >> (64 - 3)));
                    case 4:   return new UInt128(value.lo << 4,     (value.hi << 4)  | (value.lo >> (64 - 4)));
                    case 5:   return new UInt128(value.lo << 5,     (value.hi << 5)  | (value.lo >> (64 - 5)));
                    case 6:   return new UInt128(value.lo << 6,     (value.hi << 6)  | (value.lo >> (64 - 6)));
                    case 7:   return new UInt128(value.lo << 7,     (value.hi << 7)  | (value.lo >> (64 - 7)));
                    case 8:   return new UInt128(value.lo << 8,     (value.hi << 8)  | (value.lo >> (64 - 8)));
                    case 9:   return new UInt128(value.lo << 9,     (value.hi << 9)  | (value.lo >> (64 - 9)));
                    case 10:  return new UInt128(value.lo << 10,    (value.hi << 10) | (value.lo >> (64 - 10)));
                    case 11:  return new UInt128(value.lo << 11,    (value.hi << 11) | (value.lo >> (64 - 11)));
                    case 12:  return new UInt128(value.lo << 12,    (value.hi << 12) | (value.lo >> (64 - 12)));
                    case 13:  return new UInt128(value.lo << 13,    (value.hi << 13) | (value.lo >> (64 - 13)));
                    case 14:  return new UInt128(value.lo << 14,    (value.hi << 14) | (value.lo >> (64 - 14)));
                    case 15:  return new UInt128(value.lo << 15,    (value.hi << 15) | (value.lo >> (64 - 15)));
                    case 16:  return new UInt128(value.lo << 16,    (value.hi << 16) | (value.lo >> (64 - 16)));
                    case 17:  return new UInt128(value.lo << 17,    (value.hi << 17) | (value.lo >> (64 - 17)));
                    case 18:  return new UInt128(value.lo << 18,    (value.hi << 18) | (value.lo >> (64 - 18)));
                    case 19:  return new UInt128(value.lo << 19,    (value.hi << 19) | (value.lo >> (64 - 19)));
                    case 20:  return new UInt128(value.lo << 20,    (value.hi << 20) | (value.lo >> (64 - 20)));
                    case 21:  return new UInt128(value.lo << 21,    (value.hi << 21) | (value.lo >> (64 - 21)));
                    case 22:  return new UInt128(value.lo << 22,    (value.hi << 22) | (value.lo >> (64 - 22)));
                    case 23:  return new UInt128(value.lo << 23,    (value.hi << 23) | (value.lo >> (64 - 23)));
                    case 24:  return new UInt128(value.lo << 24,    (value.hi << 24) | (value.lo >> (64 - 24)));
                    case 25:  return new UInt128(value.lo << 25,    (value.hi << 25) | (value.lo >> (64 - 25)));
                    case 26:  return new UInt128(value.lo << 26,    (value.hi << 26) | (value.lo >> (64 - 26)));
                    case 27:  return new UInt128(value.lo << 27,    (value.hi << 27) | (value.lo >> (64 - 27)));
                    case 28:  return new UInt128(value.lo << 28,    (value.hi << 28) | (value.lo >> (64 - 28)));
                    case 29:  return new UInt128(value.lo << 29,    (value.hi << 29) | (value.lo >> (64 - 29)));
                    case 30:  return new UInt128(value.lo << 30,    (value.hi << 30) | (value.lo >> (64 - 30)));
                    case 31:  return new UInt128(value.lo << 31,    (value.hi << 31) | (value.lo >> (64 - 31)));
                    case 32:  return new UInt128(value.lo << 32,    (value.hi << 32) | (value.lo >> (64 - 32)));
                    case 33:  return new UInt128(value.lo << 33,    (value.hi << 33) | (value.lo >> (64 - 33)));
                    case 34:  return new UInt128(value.lo << 34,    (value.hi << 34) | (value.lo >> (64 - 34)));
                    case 35:  return new UInt128(value.lo << 35,    (value.hi << 35) | (value.lo >> (64 - 35)));
                    case 36:  return new UInt128(value.lo << 36,    (value.hi << 36) | (value.lo >> (64 - 36)));
                    case 37:  return new UInt128(value.lo << 37,    (value.hi << 37) | (value.lo >> (64 - 37)));
                    case 38:  return new UInt128(value.lo << 38,    (value.hi << 38) | (value.lo >> (64 - 38)));
                    case 39:  return new UInt128(value.lo << 39,    (value.hi << 39) | (value.lo >> (64 - 39)));
                    case 40:  return new UInt128(value.lo << 40,    (value.hi << 40) | (value.lo >> (64 - 40)));
                    case 41:  return new UInt128(value.lo << 41,    (value.hi << 41) | (value.lo >> (64 - 41)));
                    case 42:  return new UInt128(value.lo << 42,    (value.hi << 42) | (value.lo >> (64 - 42)));
                    case 43:  return new UInt128(value.lo << 43,    (value.hi << 43) | (value.lo >> (64 - 43)));
                    case 44:  return new UInt128(value.lo << 44,    (value.hi << 44) | (value.lo >> (64 - 44)));
                    case 45:  return new UInt128(value.lo << 45,    (value.hi << 45) | (value.lo >> (64 - 45)));
                    case 46:  return new UInt128(value.lo << 46,    (value.hi << 46) | (value.lo >> (64 - 46)));
                    case 47:  return new UInt128(value.lo << 47,    (value.hi << 47) | (value.lo >> (64 - 47)));
                    case 48:  return new UInt128(value.lo << 48,    (value.hi << 48) | (value.lo >> (64 - 48)));
                    case 49:  return new UInt128(value.lo << 49,    (value.hi << 49) | (value.lo >> (64 - 49)));
                    case 50:  return new UInt128(value.lo << 50,    (value.hi << 50) | (value.lo >> (64 - 50)));
                    case 51:  return new UInt128(value.lo << 51,    (value.hi << 51) | (value.lo >> (64 - 51)));
                    case 52:  return new UInt128(value.lo << 52,    (value.hi << 52) | (value.lo >> (64 - 52)));
                    case 53:  return new UInt128(value.lo << 53,    (value.hi << 53) | (value.lo >> (64 - 53)));
                    case 54:  return new UInt128(value.lo << 54,    (value.hi << 54) | (value.lo >> (64 - 54)));
                    case 55:  return new UInt128(value.lo << 55,    (value.hi << 55) | (value.lo >> (64 - 55)));
                    case 56:  return new UInt128(value.lo << 56,    (value.hi << 56) | (value.lo >> (64 - 56)));
                    case 57:  return new UInt128(value.lo << 57,    (value.hi << 57) | (value.lo >> (64 - 57)));
                    case 58:  return new UInt128(value.lo << 58,    (value.hi << 58) | (value.lo >> (64 - 58)));
                    case 59:  return new UInt128(value.lo << 59,    (value.hi << 59) | (value.lo >> (64 - 59)));
                    case 60:  return new UInt128(value.lo << 60,    (value.hi << 60) | (value.lo >> (64 - 60)));
                    case 61:  return new UInt128(value.lo << 61,    (value.hi << 61) | (value.lo >> (64 - 61)));
                    case 62:  return new UInt128(value.lo << 62,    (value.hi << 62) | (value.lo >> (64 - 62)));
                    case 63:  return new UInt128(value.lo << 63,    (value.hi << 63) | (value.lo >> (64 - 63)));
                    case 64:  return new UInt128(0,     value.lo);
                    case 65:  return new UInt128(0,     value.lo << 1);
                    case 66:  return new UInt128(0,     value.lo << 2);
                    case 67:  return new UInt128(0,     value.lo << 3);
                    case 68:  return new UInt128(0,     value.lo << 4);
                    case 69:  return new UInt128(0,     value.lo << 5);
                    case 70:  return new UInt128(0,     value.lo << 6);
                    case 71:  return new UInt128(0,     value.lo << 7);
                    case 72:  return new UInt128(0,     value.lo << 8);
                    case 73:  return new UInt128(0,     value.lo << 9);
                    case 74:  return new UInt128(0,     value.lo << 10);
                    case 75:  return new UInt128(0,     value.lo << 11);
                    case 76:  return new UInt128(0,     value.lo << 12);
                    case 77:  return new UInt128(0,     value.lo << 13);
                    case 78:  return new UInt128(0,     value.lo << 14);
                    case 79:  return new UInt128(0,     value.lo << 15);
                    case 80:  return new UInt128(0,     value.lo << 16);
                    case 81:  return new UInt128(0,     value.lo << 17);
                    case 82:  return new UInt128(0,     value.lo << 18);
                    case 83:  return new UInt128(0,     value.lo << 19);
                    case 84:  return new UInt128(0,     value.lo << 20);
                    case 85:  return new UInt128(0,     value.lo << 21);
                    case 86:  return new UInt128(0,     value.lo << 22);
                    case 87:  return new UInt128(0,     value.lo << 23);
                    case 88:  return new UInt128(0,     value.lo << 24);
                    case 89:  return new UInt128(0,     value.lo << 25);
                    case 90:  return new UInt128(0,     value.lo << 26);
                    case 91:  return new UInt128(0,     value.lo << 27);
                    case 92:  return new UInt128(0,     value.lo << 28);
                    case 93:  return new UInt128(0,     value.lo << 29);
                    case 94:  return new UInt128(0,     value.lo << 30);
                    case 95:  return new UInt128(0,     value.lo << 31);
                    case 96:  return new UInt128(0,     value.lo << 32);
                    case 97:  return new UInt128(0,     value.lo << 33);
                    case 98:  return new UInt128(0,     value.lo << 34);
                    case 99:  return new UInt128(0,     value.lo << 35);
                    case 100: return new UInt128(0,     value.lo << 36);
                    case 101: return new UInt128(0,     value.lo << 37);
                    case 102: return new UInt128(0,     value.lo << 38);
                    case 103: return new UInt128(0,     value.lo << 39);
                    case 104: return new UInt128(0,     value.lo << 40);
                    case 105: return new UInt128(0,     value.lo << 41);
                    case 106: return new UInt128(0,     value.lo << 42);
                    case 107: return new UInt128(0,     value.lo << 43);
                    case 108: return new UInt128(0,     value.lo << 44);
                    case 109: return new UInt128(0,     value.lo << 45);
                    case 110: return new UInt128(0,     value.lo << 46);
                    case 111: return new UInt128(0,     value.lo << 47);
                    case 112: return new UInt128(0,     value.lo << 48);
                    case 113: return new UInt128(0,     value.lo << 49);
                    case 114: return new UInt128(0,     value.lo << 50);
                    case 115: return new UInt128(0,     value.lo << 51);
                    case 116: return new UInt128(0,     value.lo << 52);
                    case 117: return new UInt128(0,     value.lo << 53);
                    case 118: return new UInt128(0,     value.lo << 54);
                    case 119: return new UInt128(0,     value.lo << 55);
                    case 120: return new UInt128(0,     value.lo << 56);
                    case 121: return new UInt128(0,     value.lo << 57);
                    case 122: return new UInt128(0,     value.lo << 58);
                    case 123: return new UInt128(0,     value.lo << 59);
                    case 124: return new UInt128(0,     value.lo << 60);
                    case 125: return new UInt128(0,     value.lo << 61);
                    case 126: return new UInt128(0,     value.lo << 62);
                    case 127: return new UInt128(0,     value.lo << 63);

                    default:  return value;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal static UInt128 shruint128(UInt128 value, int n) 
            {
                switch (n)
                {
                    case 1:   return new UInt128((value.lo >> 1)  | (value.hi << (64 - 1)),     value.hi >> 1);
                    case 2:   return new UInt128((value.lo >> 2)  | (value.hi << (64 - 2)),     value.hi >> 2);
                    case 3:   return new UInt128((value.lo >> 3)  | (value.hi << (64 - 3)),     value.hi >> 3);
                    case 4:   return new UInt128((value.lo >> 4)  | (value.hi << (64 - 4)),     value.hi >> 4);
                    case 5:   return new UInt128((value.lo >> 5)  | (value.hi << (64 - 5)),     value.hi >> 5);
                    case 6:   return new UInt128((value.lo >> 6)  | (value.hi << (64 - 6)),     value.hi >> 6);
                    case 7:   return new UInt128((value.lo >> 7)  | (value.hi << (64 - 7)),     value.hi >> 7);
                    case 8:   return new UInt128((value.lo >> 8)  | (value.hi << (64 - 8)),     value.hi >> 8);
                    case 9:   return new UInt128((value.lo >> 9)  | (value.hi << (64 - 9)),     value.hi >> 9);
                    case 10:  return new UInt128((value.lo >> 10) | (value.hi << (64 - 10)),    value.hi >> 10);
                    case 11:  return new UInt128((value.lo >> 11) | (value.hi << (64 - 11)),    value.hi >> 11);
                    case 12:  return new UInt128((value.lo >> 12) | (value.hi << (64 - 12)),    value.hi >> 12);
                    case 13:  return new UInt128((value.lo >> 13) | (value.hi << (64 - 13)),    value.hi >> 13);
                    case 14:  return new UInt128((value.lo >> 14) | (value.hi << (64 - 14)),    value.hi >> 14);
                    case 15:  return new UInt128((value.lo >> 15) | (value.hi << (64 - 15)),    value.hi >> 15);
                    case 16:  return new UInt128((value.lo >> 16) | (value.hi << (64 - 16)),    value.hi >> 16);
                    case 17:  return new UInt128((value.lo >> 17) | (value.hi << (64 - 17)),    value.hi >> 17);
                    case 18:  return new UInt128((value.lo >> 18) | (value.hi << (64 - 18)),    value.hi >> 18);
                    case 19:  return new UInt128((value.lo >> 19) | (value.hi << (64 - 19)),    value.hi >> 19);
                    case 20:  return new UInt128((value.lo >> 20) | (value.hi << (64 - 20)),    value.hi >> 20);
                    case 21:  return new UInt128((value.lo >> 21) | (value.hi << (64 - 21)),    value.hi >> 21);
                    case 22:  return new UInt128((value.lo >> 22) | (value.hi << (64 - 22)),    value.hi >> 22);
                    case 23:  return new UInt128((value.lo >> 23) | (value.hi << (64 - 23)),    value.hi >> 23);
                    case 24:  return new UInt128((value.lo >> 24) | (value.hi << (64 - 24)),    value.hi >> 24);
                    case 25:  return new UInt128((value.lo >> 25) | (value.hi << (64 - 25)),    value.hi >> 25);
                    case 26:  return new UInt128((value.lo >> 26) | (value.hi << (64 - 26)),    value.hi >> 26);
                    case 27:  return new UInt128((value.lo >> 27) | (value.hi << (64 - 27)),    value.hi >> 27);
                    case 28:  return new UInt128((value.lo >> 28) | (value.hi << (64 - 28)),    value.hi >> 28);
                    case 29:  return new UInt128((value.lo >> 29) | (value.hi << (64 - 29)),    value.hi >> 29);
                    case 30:  return new UInt128((value.lo >> 30) | (value.hi << (64 - 30)),    value.hi >> 30);
                    case 31:  return new UInt128((value.lo >> 31) | (value.hi << (64 - 31)),    value.hi >> 31);
                    case 32:  return new UInt128((value.lo >> 32) | (value.hi << (64 - 32)),    value.hi >> 32);
                    case 33:  return new UInt128((value.lo >> 33) | (value.hi << (64 - 33)),    value.hi >> 33);
                    case 34:  return new UInt128((value.lo >> 34) | (value.hi << (64 - 34)),    value.hi >> 34);
                    case 35:  return new UInt128((value.lo >> 35) | (value.hi << (64 - 35)),    value.hi >> 35);
                    case 36:  return new UInt128((value.lo >> 36) | (value.hi << (64 - 36)),    value.hi >> 36);
                    case 37:  return new UInt128((value.lo >> 37) | (value.hi << (64 - 37)),    value.hi >> 37);
                    case 38:  return new UInt128((value.lo >> 38) | (value.hi << (64 - 38)),    value.hi >> 38);
                    case 39:  return new UInt128((value.lo >> 39) | (value.hi << (64 - 39)),    value.hi >> 39);
                    case 40:  return new UInt128((value.lo >> 40) | (value.hi << (64 - 40)),    value.hi >> 40);
                    case 41:  return new UInt128((value.lo >> 41) | (value.hi << (64 - 41)),    value.hi >> 41);
                    case 42:  return new UInt128((value.lo >> 42) | (value.hi << (64 - 42)),    value.hi >> 42);
                    case 43:  return new UInt128((value.lo >> 43) | (value.hi << (64 - 43)),    value.hi >> 43);
                    case 44:  return new UInt128((value.lo >> 44) | (value.hi << (64 - 44)),    value.hi >> 44);
                    case 45:  return new UInt128((value.lo >> 45) | (value.hi << (64 - 45)),    value.hi >> 45);
                    case 46:  return new UInt128((value.lo >> 46) | (value.hi << (64 - 46)),    value.hi >> 46);
                    case 47:  return new UInt128((value.lo >> 47) | (value.hi << (64 - 47)),    value.hi >> 47);
                    case 48:  return new UInt128((value.lo >> 48) | (value.hi << (64 - 48)),    value.hi >> 48);
                    case 49:  return new UInt128((value.lo >> 49) | (value.hi << (64 - 49)),    value.hi >> 49);
                    case 50:  return new UInt128((value.lo >> 50) | (value.hi << (64 - 50)),    value.hi >> 50);
                    case 51:  return new UInt128((value.lo >> 51) | (value.hi << (64 - 51)),    value.hi >> 51);
                    case 52:  return new UInt128((value.lo >> 52) | (value.hi << (64 - 52)),    value.hi >> 52);
                    case 53:  return new UInt128((value.lo >> 53) | (value.hi << (64 - 53)),    value.hi >> 53);
                    case 54:  return new UInt128((value.lo >> 54) | (value.hi << (64 - 54)),    value.hi >> 54);
                    case 55:  return new UInt128((value.lo >> 55) | (value.hi << (64 - 55)),    value.hi >> 55);
                    case 56:  return new UInt128((value.lo >> 56) | (value.hi << (64 - 56)),    value.hi >> 56);
                    case 57:  return new UInt128((value.lo >> 57) | (value.hi << (64 - 57)),    value.hi >> 57);
                    case 58:  return new UInt128((value.lo >> 58) | (value.hi << (64 - 58)),    value.hi >> 58);
                    case 59:  return new UInt128((value.lo >> 59) | (value.hi << (64 - 59)),    value.hi >> 59);
                    case 60:  return new UInt128((value.lo >> 60) | (value.hi << (64 - 60)),    value.hi >> 60);
                    case 61:  return new UInt128((value.lo >> 61) | (value.hi << (64 - 61)),    value.hi >> 61);
                    case 62:  return new UInt128((value.lo >> 62) | (value.hi << (64 - 62)),    value.hi >> 62);
                    case 63:  return new UInt128((value.lo >> 63) | (value.hi << (64 - 63)),    value.hi >> 63);
                    case 64:  return new UInt128(value.hi,           0);
                    case 65:  return new UInt128(value.hi >> 1,      0);
                    case 66:  return new UInt128(value.hi >> 2,      0);
                    case 67:  return new UInt128(value.hi >> 3,      0);
                    case 68:  return new UInt128(value.hi >> 4,      0);
                    case 69:  return new UInt128(value.hi >> 5,      0);
                    case 70:  return new UInt128(value.hi >> 6,      0);
                    case 71:  return new UInt128(value.hi >> 7,      0);
                    case 72:  return new UInt128(value.hi >> 8,      0);
                    case 73:  return new UInt128(value.hi >> 9,      0);
                    case 74:  return new UInt128(value.hi >> 10,     0);
                    case 75:  return new UInt128(value.hi >> 11,     0);
                    case 76:  return new UInt128(value.hi >> 12,     0);
                    case 77:  return new UInt128(value.hi >> 13,     0);
                    case 78:  return new UInt128(value.hi >> 14,     0);
                    case 79:  return new UInt128(value.hi >> 15,     0);
                    case 80:  return new UInt128(value.hi >> 16,     0);
                    case 81:  return new UInt128(value.hi >> 17,     0);
                    case 82:  return new UInt128(value.hi >> 18,     0);
                    case 83:  return new UInt128(value.hi >> 19,     0);
                    case 84:  return new UInt128(value.hi >> 20,     0);
                    case 85:  return new UInt128(value.hi >> 21,     0);
                    case 86:  return new UInt128(value.hi >> 22,     0);
                    case 87:  return new UInt128(value.hi >> 23,     0);
                    case 88:  return new UInt128(value.hi >> 24,     0);
                    case 89:  return new UInt128(value.hi >> 25,     0);
                    case 90:  return new UInt128(value.hi >> 26,     0);
                    case 91:  return new UInt128(value.hi >> 27,     0);
                    case 92:  return new UInt128(value.hi >> 28,     0);
                    case 93:  return new UInt128(value.hi >> 29,     0);
                    case 94:  return new UInt128(value.hi >> 30,     0);
                    case 95:  return new UInt128(value.hi >> 31,     0);
                    case 96:  return new UInt128(value.hi >> 32,     0);
                    case 97:  return new UInt128(value.hi >> 33,     0);
                    case 98:  return new UInt128(value.hi >> 34,     0);
                    case 99:  return new UInt128(value.hi >> 35,     0);
                    case 100: return new UInt128(value.hi >> 36,     0);
                    case 101: return new UInt128(value.hi >> 37,     0);
                    case 102: return new UInt128(value.hi >> 38,     0);
                    case 103: return new UInt128(value.hi >> 39,     0);
                    case 104: return new UInt128(value.hi >> 40,     0);
                    case 105: return new UInt128(value.hi >> 41,     0);
                    case 106: return new UInt128(value.hi >> 42,     0);
                    case 107: return new UInt128(value.hi >> 43,     0);
                    case 108: return new UInt128(value.hi >> 44,     0);
                    case 109: return new UInt128(value.hi >> 45,     0);
                    case 110: return new UInt128(value.hi >> 46,     0);
                    case 111: return new UInt128(value.hi >> 47,     0);
                    case 112: return new UInt128(value.hi >> 48,     0);
                    case 113: return new UInt128(value.hi >> 49,     0);
                    case 114: return new UInt128(value.hi >> 50,     0);
                    case 115: return new UInt128(value.hi >> 51,     0);
                    case 116: return new UInt128(value.hi >> 52,     0);
                    case 117: return new UInt128(value.hi >> 53,     0);
                    case 118: return new UInt128(value.hi >> 54,     0);
                    case 119: return new UInt128(value.hi >> 55,     0);
                    case 120: return new UInt128(value.hi >> 56,     0);
                    case 121: return new UInt128(value.hi >> 57,     0);
                    case 122: return new UInt128(value.hi >> 58,     0);
                    case 123: return new UInt128(value.hi >> 59,     0);
                    case 124: return new UInt128(value.hi >> 60,     0);
                    case 125: return new UInt128(value.hi >> 61,     0);
                    case 126: return new UInt128(value.hi >> 62,     0);
                    case 127: return new UInt128(value.hi >> 63,     0);

                    default:  return value;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal static Int128 sarint128(Int128 value, int n) 
            {
                switch (n)
                {
                    case 1:   return new Int128((value.intern.lo >> 1)  | (value.intern.hi << (64 - 1)),     (ulong)((long)value.intern.hi >> 1));
                    case 2:   return new Int128((value.intern.lo >> 2)  | (value.intern.hi << (64 - 2)),     (ulong)((long)value.intern.hi >> 2));
                    case 3:   return new Int128((value.intern.lo >> 3)  | (value.intern.hi << (64 - 3)),     (ulong)((long)value.intern.hi >> 3));
                    case 4:   return new Int128((value.intern.lo >> 4)  | (value.intern.hi << (64 - 4)),     (ulong)((long)value.intern.hi >> 4));
                    case 5:   return new Int128((value.intern.lo >> 5)  | (value.intern.hi << (64 - 5)),     (ulong)((long)value.intern.hi >> 5));
                    case 6:   return new Int128((value.intern.lo >> 6)  | (value.intern.hi << (64 - 6)),     (ulong)((long)value.intern.hi >> 6));
                    case 7:   return new Int128((value.intern.lo >> 7)  | (value.intern.hi << (64 - 7)),     (ulong)((long)value.intern.hi >> 7));
                    case 8:   return new Int128((value.intern.lo >> 8)  | (value.intern.hi << (64 - 8)),     (ulong)((long)value.intern.hi >> 8));
                    case 9:   return new Int128((value.intern.lo >> 9)  | (value.intern.hi << (64 - 9)),     (ulong)((long)value.intern.hi >> 9));
                    case 10:  return new Int128((value.intern.lo >> 10) | (value.intern.hi << (64 - 10)),    (ulong)((long)value.intern.hi >> 10));
                    case 11:  return new Int128((value.intern.lo >> 11) | (value.intern.hi << (64 - 11)),    (ulong)((long)value.intern.hi >> 11));
                    case 12:  return new Int128((value.intern.lo >> 12) | (value.intern.hi << (64 - 12)),    (ulong)((long)value.intern.hi >> 12));
                    case 13:  return new Int128((value.intern.lo >> 13) | (value.intern.hi << (64 - 13)),    (ulong)((long)value.intern.hi >> 13));
                    case 14:  return new Int128((value.intern.lo >> 14) | (value.intern.hi << (64 - 14)),    (ulong)((long)value.intern.hi >> 14));
                    case 15:  return new Int128((value.intern.lo >> 15) | (value.intern.hi << (64 - 15)),    (ulong)((long)value.intern.hi >> 15));
                    case 16:  return new Int128((value.intern.lo >> 16) | (value.intern.hi << (64 - 16)),    (ulong)((long)value.intern.hi >> 16));
                    case 17:  return new Int128((value.intern.lo >> 17) | (value.intern.hi << (64 - 17)),    (ulong)((long)value.intern.hi >> 17));
                    case 18:  return new Int128((value.intern.lo >> 18) | (value.intern.hi << (64 - 18)),    (ulong)((long)value.intern.hi >> 18));
                    case 19:  return new Int128((value.intern.lo >> 19) | (value.intern.hi << (64 - 19)),    (ulong)((long)value.intern.hi >> 19));
                    case 20:  return new Int128((value.intern.lo >> 20) | (value.intern.hi << (64 - 20)),    (ulong)((long)value.intern.hi >> 20));
                    case 21:  return new Int128((value.intern.lo >> 21) | (value.intern.hi << (64 - 21)),    (ulong)((long)value.intern.hi >> 21));
                    case 22:  return new Int128((value.intern.lo >> 22) | (value.intern.hi << (64 - 22)),    (ulong)((long)value.intern.hi >> 22));
                    case 23:  return new Int128((value.intern.lo >> 23) | (value.intern.hi << (64 - 23)),    (ulong)((long)value.intern.hi >> 23));
                    case 24:  return new Int128((value.intern.lo >> 24) | (value.intern.hi << (64 - 24)),    (ulong)((long)value.intern.hi >> 24));
                    case 25:  return new Int128((value.intern.lo >> 25) | (value.intern.hi << (64 - 25)),    (ulong)((long)value.intern.hi >> 25));
                    case 26:  return new Int128((value.intern.lo >> 26) | (value.intern.hi << (64 - 26)),    (ulong)((long)value.intern.hi >> 26));
                    case 27:  return new Int128((value.intern.lo >> 27) | (value.intern.hi << (64 - 27)),    (ulong)((long)value.intern.hi >> 27));
                    case 28:  return new Int128((value.intern.lo >> 28) | (value.intern.hi << (64 - 28)),    (ulong)((long)value.intern.hi >> 28));
                    case 29:  return new Int128((value.intern.lo >> 29) | (value.intern.hi << (64 - 29)),    (ulong)((long)value.intern.hi >> 29));
                    case 30:  return new Int128((value.intern.lo >> 30) | (value.intern.hi << (64 - 30)),    (ulong)((long)value.intern.hi >> 30));
                    case 31:  return new Int128((value.intern.lo >> 31) | (value.intern.hi << (64 - 31)),    (ulong)((long)value.intern.hi >> 31));
                    case 32:  return new Int128((value.intern.lo >> 32) | (value.intern.hi << (64 - 32)),    (ulong)((long)value.intern.hi >> 32));
                    case 33:  return new Int128((value.intern.lo >> 33) | (value.intern.hi << (64 - 33)),    (ulong)((long)value.intern.hi >> 33));
                    case 34:  return new Int128((value.intern.lo >> 34) | (value.intern.hi << (64 - 34)),    (ulong)((long)value.intern.hi >> 34));
                    case 35:  return new Int128((value.intern.lo >> 35) | (value.intern.hi << (64 - 35)),    (ulong)((long)value.intern.hi >> 35));
                    case 36:  return new Int128((value.intern.lo >> 36) | (value.intern.hi << (64 - 36)),    (ulong)((long)value.intern.hi >> 36));
                    case 37:  return new Int128((value.intern.lo >> 37) | (value.intern.hi << (64 - 37)),    (ulong)((long)value.intern.hi >> 37));
                    case 38:  return new Int128((value.intern.lo >> 38) | (value.intern.hi << (64 - 38)),    (ulong)((long)value.intern.hi >> 38));
                    case 39:  return new Int128((value.intern.lo >> 39) | (value.intern.hi << (64 - 39)),    (ulong)((long)value.intern.hi >> 39));
                    case 40:  return new Int128((value.intern.lo >> 40) | (value.intern.hi << (64 - 40)),    (ulong)((long)value.intern.hi >> 40));
                    case 41:  return new Int128((value.intern.lo >> 41) | (value.intern.hi << (64 - 41)),    (ulong)((long)value.intern.hi >> 41));
                    case 42:  return new Int128((value.intern.lo >> 42) | (value.intern.hi << (64 - 42)),    (ulong)((long)value.intern.hi >> 42));
                    case 43:  return new Int128((value.intern.lo >> 43) | (value.intern.hi << (64 - 43)),    (ulong)((long)value.intern.hi >> 43));
                    case 44:  return new Int128((value.intern.lo >> 44) | (value.intern.hi << (64 - 44)),    (ulong)((long)value.intern.hi >> 44));
                    case 45:  return new Int128((value.intern.lo >> 45) | (value.intern.hi << (64 - 45)),    (ulong)((long)value.intern.hi >> 45));
                    case 46:  return new Int128((value.intern.lo >> 46) | (value.intern.hi << (64 - 46)),    (ulong)((long)value.intern.hi >> 46));
                    case 47:  return new Int128((value.intern.lo >> 47) | (value.intern.hi << (64 - 47)),    (ulong)((long)value.intern.hi >> 47));
                    case 48:  return new Int128((value.intern.lo >> 48) | (value.intern.hi << (64 - 48)),    (ulong)((long)value.intern.hi >> 48));
                    case 49:  return new Int128((value.intern.lo >> 49) | (value.intern.hi << (64 - 49)),    (ulong)((long)value.intern.hi >> 49));
                    case 50:  return new Int128((value.intern.lo >> 50) | (value.intern.hi << (64 - 50)),    (ulong)((long)value.intern.hi >> 50));
                    case 51:  return new Int128((value.intern.lo >> 51) | (value.intern.hi << (64 - 51)),    (ulong)((long)value.intern.hi >> 51));
                    case 52:  return new Int128((value.intern.lo >> 52) | (value.intern.hi << (64 - 52)),    (ulong)((long)value.intern.hi >> 52));
                    case 53:  return new Int128((value.intern.lo >> 53) | (value.intern.hi << (64 - 53)),    (ulong)((long)value.intern.hi >> 53));
                    case 54:  return new Int128((value.intern.lo >> 54) | (value.intern.hi << (64 - 54)),    (ulong)((long)value.intern.hi >> 54));
                    case 55:  return new Int128((value.intern.lo >> 55) | (value.intern.hi << (64 - 55)),    (ulong)((long)value.intern.hi >> 55));
                    case 56:  return new Int128((value.intern.lo >> 56) | (value.intern.hi << (64 - 56)),    (ulong)((long)value.intern.hi >> 56));
                    case 57:  return new Int128((value.intern.lo >> 57) | (value.intern.hi << (64 - 57)),    (ulong)((long)value.intern.hi >> 57));
                    case 58:  return new Int128((value.intern.lo >> 58) | (value.intern.hi << (64 - 58)),    (ulong)((long)value.intern.hi >> 58));
                    case 59:  return new Int128((value.intern.lo >> 59) | (value.intern.hi << (64 - 59)),    (ulong)((long)value.intern.hi >> 59));
                    case 60:  return new Int128((value.intern.lo >> 60) | (value.intern.hi << (64 - 60)),    (ulong)((long)value.intern.hi >> 60));
                    case 61:  return new Int128((value.intern.lo >> 61) | (value.intern.hi << (64 - 61)),    (ulong)((long)value.intern.hi >> 61));
                    case 62:  return new Int128((value.intern.lo >> 62) | (value.intern.hi << (64 - 62)),    (ulong)((long)value.intern.hi >> 62));
                    case 63:  return new Int128((value.intern.lo >> 63) | (value.intern.hi << (64 - 63)),    (ulong)((long)value.intern.hi >> 63));
                    case 64:  return new Int128((long)value.intern.hi,           (long)value.intern.hi >> 63);
                    case 65:  return new Int128((long)value.intern.hi >> 1,      (long)value.intern.hi >> 63);
                    case 66:  return new Int128((long)value.intern.hi >> 2,      (long)value.intern.hi >> 63);
                    case 67:  return new Int128((long)value.intern.hi >> 3,      (long)value.intern.hi >> 63);
                    case 68:  return new Int128((long)value.intern.hi >> 4,      (long)value.intern.hi >> 63);
                    case 69:  return new Int128((long)value.intern.hi >> 5,      (long)value.intern.hi >> 63);
                    case 70:  return new Int128((long)value.intern.hi >> 6,      (long)value.intern.hi >> 63);
                    case 71:  return new Int128((long)value.intern.hi >> 7,      (long)value.intern.hi >> 63);
                    case 72:  return new Int128((long)value.intern.hi >> 8,      (long)value.intern.hi >> 63);
                    case 73:  return new Int128((long)value.intern.hi >> 9,      (long)value.intern.hi >> 63);
                    case 74:  return new Int128((long)value.intern.hi >> 10,     (long)value.intern.hi >> 63);
                    case 75:  return new Int128((long)value.intern.hi >> 11,     (long)value.intern.hi >> 63);
                    case 76:  return new Int128((long)value.intern.hi >> 12,     (long)value.intern.hi >> 63);
                    case 77:  return new Int128((long)value.intern.hi >> 13,     (long)value.intern.hi >> 63);
                    case 78:  return new Int128((long)value.intern.hi >> 14,     (long)value.intern.hi >> 63);
                    case 79:  return new Int128((long)value.intern.hi >> 15,     (long)value.intern.hi >> 63);
                    case 80:  return new Int128((long)value.intern.hi >> 16,     (long)value.intern.hi >> 63);
                    case 81:  return new Int128((long)value.intern.hi >> 17,     (long)value.intern.hi >> 63);
                    case 82:  return new Int128((long)value.intern.hi >> 18,     (long)value.intern.hi >> 63);
                    case 83:  return new Int128((long)value.intern.hi >> 19,     (long)value.intern.hi >> 63);
                    case 84:  return new Int128((long)value.intern.hi >> 20,     (long)value.intern.hi >> 63);
                    case 85:  return new Int128((long)value.intern.hi >> 21,     (long)value.intern.hi >> 63);
                    case 86:  return new Int128((long)value.intern.hi >> 22,     (long)value.intern.hi >> 63);
                    case 87:  return new Int128((long)value.intern.hi >> 23,     (long)value.intern.hi >> 63);
                    case 88:  return new Int128((long)value.intern.hi >> 24,     (long)value.intern.hi >> 63);
                    case 89:  return new Int128((long)value.intern.hi >> 25,     (long)value.intern.hi >> 63);
                    case 90:  return new Int128((long)value.intern.hi >> 26,     (long)value.intern.hi >> 63);
                    case 91:  return new Int128((long)value.intern.hi >> 27,     (long)value.intern.hi >> 63);
                    case 92:  return new Int128((long)value.intern.hi >> 28,     (long)value.intern.hi >> 63);
                    case 93:  return new Int128((long)value.intern.hi >> 29,     (long)value.intern.hi >> 63);
                    case 94:  return new Int128((long)value.intern.hi >> 30,     (long)value.intern.hi >> 63);
                    case 95:  return new Int128((long)value.intern.hi >> 31,     (long)value.intern.hi >> 63);
                    case 96:  return new Int128((long)value.intern.hi >> 32,     (long)value.intern.hi >> 63);
                    case 97:  return new Int128((long)value.intern.hi >> 33,     (long)value.intern.hi >> 63);
                    case 98:  return new Int128((long)value.intern.hi >> 34,     (long)value.intern.hi >> 63);
                    case 99:  return new Int128((long)value.intern.hi >> 35,     (long)value.intern.hi >> 63);
                    case 100: return new Int128((long)value.intern.hi >> 36,     (long)value.intern.hi >> 63);
                    case 101: return new Int128((long)value.intern.hi >> 37,     (long)value.intern.hi >> 63);
                    case 102: return new Int128((long)value.intern.hi >> 38,     (long)value.intern.hi >> 63);
                    case 103: return new Int128((long)value.intern.hi >> 39,     (long)value.intern.hi >> 63);
                    case 104: return new Int128((long)value.intern.hi >> 40,     (long)value.intern.hi >> 63);
                    case 105: return new Int128((long)value.intern.hi >> 41,     (long)value.intern.hi >> 63);
                    case 106: return new Int128((long)value.intern.hi >> 42,     (long)value.intern.hi >> 63);
                    case 107: return new Int128((long)value.intern.hi >> 43,     (long)value.intern.hi >> 63);
                    case 108: return new Int128((long)value.intern.hi >> 44,     (long)value.intern.hi >> 63);
                    case 109: return new Int128((long)value.intern.hi >> 45,     (long)value.intern.hi >> 63);
                    case 110: return new Int128((long)value.intern.hi >> 46,     (long)value.intern.hi >> 63);
                    case 111: return new Int128((long)value.intern.hi >> 47,     (long)value.intern.hi >> 63);
                    case 112: return new Int128((long)value.intern.hi >> 48,     (long)value.intern.hi >> 63);
                    case 113: return new Int128((long)value.intern.hi >> 49,     (long)value.intern.hi >> 63);
                    case 114: return new Int128((long)value.intern.hi >> 50,     (long)value.intern.hi >> 63);
                    case 115: return new Int128((long)value.intern.hi >> 51,     (long)value.intern.hi >> 63);
                    case 116: return new Int128((long)value.intern.hi >> 52,     (long)value.intern.hi >> 63);
                    case 117: return new Int128((long)value.intern.hi >> 53,     (long)value.intern.hi >> 63);
                    case 118: return new Int128((long)value.intern.hi >> 54,     (long)value.intern.hi >> 63);
                    case 119: return new Int128((long)value.intern.hi >> 55,     (long)value.intern.hi >> 63);
                    case 120: return new Int128((long)value.intern.hi >> 56,     (long)value.intern.hi >> 63);
                    case 121: return new Int128((long)value.intern.hi >> 57,     (long)value.intern.hi >> 63);
                    case 122: return new Int128((long)value.intern.hi >> 58,     (long)value.intern.hi >> 63);
                    case 123: return new Int128((long)value.intern.hi >> 59,     (long)value.intern.hi >> 63);
                    case 124: return new Int128((long)value.intern.hi >> 60,     (long)value.intern.hi >> 63);
                    case 125: return new Int128((long)value.intern.hi >> 61,     (long)value.intern.hi >> 63);
                    case 126: return new Int128((long)value.intern.hi >> 62,     (long)value.intern.hi >> 63);
                    case 127: return new Int128((long)value.intern.hi >> 63,     (long)value.intern.hi >> 63);

                    default:  return value;
                }
            }
        }
    }
}